//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment_Portfolio_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int FriendId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int CustomerCustId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
